### ISSUE TITLE
ERROR  Can't locate path create_widgets_table.php.stub

### ISSUE THREAD

**Issue by sunw31** [lara-zeus/rain#18]
php artisan vendor:publish --tag=zeus-rain-migrations

 INFO  Publishing [zeus-rain-migrations] assets.

 ERROR  Can't locate path: <vendor/lara-zeus/rain/src/../database/migrations/create_widgets_table.php.stub>.

**Comment by atmonshi** [comment]
thank you for the report, fixed in the new release.
