### ISSUE TITLE
[Bug]: Uncaught TypeError: Cannot read properties of null (reading 'layout_title')

### ISSUE THREAD

**Issue by KarolLitman** [lara-zeus/rain#38]
### What happened?

The problem occurs when creating a dashboard. Error in browser console. No positive click on "add dashboard" and "save"
The problem occurs with vanilla filament.
Filament version: 3.2.52
Livewire: 3.4.9
![2024-04-05 15-10-47](https://github.com/lara-zeus/dynamic-dashboard/assets/12096570/f9fcd5ba-c811-411a-a36a-2c133fc94a3c)

### How to reproduce the bug

composer require lara-zeus/dynamic-dashboard
php artisan vendor:publish --tag=zeus-dynamic-dashboard-migrations
php artisan migrate
Add plugin DynamicDashboardPlugin::make() to AdminPanelProvider class

### Package Version

3.0.1

### PHP Version

8.3.4

### Laravel Version

11.0.7

**Comment by atmonshi** [comment]
can you update to last livewire and filament and test again
cant get the issue in the demo: https://demo.larazeus.com/admin/layouts
